var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};
$jscomp.polyfill=function(a,b,e,g){if(b){e=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var h=a[g];h in e||(e[h]={});e=e[h]}a=a[a.length-1];g=e[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function e(a){return a instanceof h?a:new h(function(b,A){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var g=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){g(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var e=a[b];a[b]=null;try{e()}catch(R){this.asyncThrow_(R)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var h=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(Q){b.reject(Q)}};h.prototype.createResolveAndReject_=function(){function a(a){return function(g){e||(e=!0,a.call(b,g))}}var b=this,e=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};h.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof h)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};h.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(Q){this.reject_(Q);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};h.prototype.reject_=function(a){this.settle_(2,a)};h.prototype.fulfill_=function(a){this.settle_(1,a)};h.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};h.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)l.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var l=new b;h.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};h.prototype.settleSameAsThenable_=function(a,b){var e=this.createResolveAndReject_();try{a.call(b,e.resolve,e.reject)}catch(R){e.reject(R)}};h.prototype.then=function(a,b){function e(a,b){return"function"==typeof a?function(b){try{g(a(b))}catch(k){l(k)}}:b}var g,l,A=new h(function(a,b){g=a;l=b});this.callWhenSettled_(e(a,g),e(b,l));return A};
h.prototype.catch=function(a){return this.then(void 0,a)};h.prototype.callWhenSettled_=function(a,b){function e(){switch(g.state_){case 1:a(g.result_);break;case 2:b(g.result_);break;default:throw Error("Unexpected state: "+g.state_);}}var g=this;null==this.onSettledCallbacks_?l.asyncExecute(e):this.onSettledCallbacks_.push(e)};h.resolve=e;h.reject=function(a){return new h(function(b,e){e(a)})};h.race=function(a){return new h(function(b,g){for(var h=$jscomp.makeIterator(a),l=h.next();!l.done;l=h.next())e(l.value).callWhenSettled_(b,
g)})};h.all=function(a){var b=$jscomp.makeIterator(a),g=b.next();return g.done?e([]):new h(function(a,h){function l(b){return function(e){A[b]=e;c--;0==c&&a(A)}}var A=[],c=0;do A.push(void 0),c++,e(g.value).callWhenSettled_(l(A.length-1),h),g=b.next();while(!g.done)})};return h},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(e){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(e||"")+"_"+b++,e)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(e){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var e=a.next();$jscomp.generator.ensureIteratorResultIsObject_(e);if(e.done)this.yieldResult=e.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(e.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,e){e?this.finallyContexts_[e]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,e){try{var g=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(g);if(!g.done)return this.context_.stop_(),g;var h=g.value}catch(l){return this.context_.yieldAllIterator_=null,this.context_.throw_(l),this.nextStep_()}this.context_.yieldAllIterator_=null;e.call(this.context_,h);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function e(b){return a.throw(b)}return new Promise(function(g,h){function l(a){a.done?g(a.value):Promise.resolve(a.value).then(b,e).then(l,h)}l(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.findInternal=function(a,b,e){a instanceof String&&(a=String(a));for(var g=a.length,h=0;h<g;h++){var l=a[h];if(b.call(e,l,h,a))return{i:h,v:l}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,e){if(null==a)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,e){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===e&&(e=b.length);e=Math.max(0,Math.min(e|0,b.length));for(var h=a.length;0<h&&0<e;)if(b[--e]!=a[--h])return!1;return 0>=h}},"es6","es3");
var coursePlayer=function(a){function b(){var b=0;k.siblings("div,a").each(function(){b+=a(this).height()});k.css("max-height","calc(100% - "+b+"px)")}function e(){a(".courseHome").removeClass("courseHome");var b=0<k.find(".enabled-true.completed-false").length?k.find(".enabled-true.completed-false:first"):k.find(".enabled-true:last");b.hasClass("courseSubItem")?b.trigger("click"):b.find(".citem").trigger("click")}function g(){la.hide()}function h(){la.show()}function l(){z=0;C=!0}function A(b){var c=
w.indexOf(b);b=k.find(".completed-false[data-id='"+b+"']:eq(0)");b.removeClass("completed-false").addClass("completed-true");if(c+1<w.length){if(b.hasClass("prereqItem"))for(c+=1;c<w.length&&(b=k.find("[data-id="+w[c]+"]"),b.removeClass("enabled-false").addClass("enabled-true"),!b.hasClass("prereqItem"));c++);else k.find(".enabled-false[data-id='"+w[c+1]+"']:eq(0)").removeClass("enabled-false").addClass("enabled-true");r.removeAttr("disabled")}else c+1==w.length&&r.attr("disabled",!0).removeClass("completeItem");
c=a(".courseItem.completed-true").length+a(".courseSubItem.completed-true").length;b=a(".courseItem.completed-false").length+a(".courseSubItem.completed-false").length;H=parseInt(100*c/(c+b));a("#courseProgressCont").find("progress").attr("value",H);a("#courseProgress").text(H+"%");100===H&&segmentTrack("Course completion",{event:"course_completion",properties:{courseId:D,courseName:wa}})}function aa(){var b=a(".container").height(),c=a("footer").is(":visible")?a("footer").height():0;b-=c;a(".wrapper-reader").height(b);
c=a(".mid-section header").height();a(".mid-section .content").height(b-c);a(".btn-content-group").height(a(".reader-lhs").height()-a(".reader-lhs header").height())}function Q(b,e){y=!0;C=!1;z=0;var k=_.template(a("#itemNotAvailableTemplate").html());c.html(k({startDate:convertDateTime(new Date(b)),endDate:convertDateTime(new Date(e))}));g();r.removeClass("completeItem")}function R(a,b){C=!0;0>["assignment","activity"].indexOf(a)&&l();g()}function ta(){var a=w.indexOf(c.data("id"))+1;a>=w.length?
setTimeout(function(){r.removeClass("completeItem").attr("disabled",!0)},500):(a=k.find("[data-id="+w[a]+"]"),a.hasClass("courseSubItem")?a.trigger("click"):a.find(".citem").trigger("click"),G.makeVisible(a))}function va(b){var c={};c.time=z;if(0<z){var e=parseInt(a("#courseTime").data("time"))+z;a("#courseTime").data("time",e).text(formatSeconds(e));z=0}postData({url:ctx+"/courses/"+D+"/items/"+b+"/completed",data:c,success:function(a,c){z=0;C=!1;A(b);ta()}},{btn:r})}function ua(){var a=document.createElement("iframe");
document.body.appendChild(a);if("undefined"!==typeof a.contentWindow.MediaSource&&a.contentWindow.MediaSource.toString()!==MediaSource.toString())return a.remove(),!0;a.remove();return!1}var c=a("#text"),la=a("#courseLoader"),k=a(".courseItems"),ba=[],w=[],r=a("#nextCourseItemBtn"),xa=a("#goToDiscussionsBtn"),na,oa,D,V,N,O=!1,H=0,P=0,ca=!1,da=!1,ea,y=!0,E=a("#prevCourseItemBtn"),z=0,C=!1,pa="",qa="",M=null,W=null,ra=null,ya,K=!0,fa=10,za=20,ha=0,u={},Aa=/^((?!chrome|android).)*safari/i.test(navigator.userAgent),
wa,G=function(){function b(b){if(0<a(".courseHome").length)return!1;a(".off-canvas-overlay").is(":visible")&&a(".off-canvas-overlay").trigger("click");a("#discussions-cont").hide();a(".mainCont").show();da=!1;a("#courseTocBtn").addClass("bg-primary");a("#courseDiscussionsBtn").removeClass("bg-primary");la.show();var d=a(b).data("type"),f=a(b).data("id");0<k.find(".selected").length&&!I&&0<z&&(e(),z=0,C=!1);k.find(".selected").removeClass("selected").removeClass("bg-secondary");a(b).addClass("selected").addClass("bg-secondary");
xa.hide();c.data("id",f);if(I){var L=k.find(".enabled-false, .enabled-true");L.index(a(b))==L.length-1?r.attr("disabled",!0):r.removeAttr("disabled");0==L.index(a(b))?E.attr("disabled",!0):E.removeAttr("disabled")}else k.find(".enabled-true:last").hasClass("selected")?-1<"link article video audio pdf file scorm".split(" ").indexOf(d)&&!k.find(".enabled-true:last").hasClass("completed-true")?r.removeAttr("disabled").addClass("completeItem"):r.attr("disabled",!0).removeClass("completeItem"):(r.removeAttr("disabled"),
k.find(".selected").hasClass("completed-true")?r.removeClass("completeItem"):-1<"link article video audio pdf file scorm".split(" ").indexOf(d)?r.addClass("completeItem"):k.hasClass("course-flow-true")?r.removeClass("completeItem").attr("disabled",!0):r.removeClass("completeItem")),k.find(".enabled-true:first").hasClass("selected")?E.attr("disabled",!0):E.removeAttr("disabled");J();ca=O=y=!1;switch(d){case "link":case "article":Ca(f,d);break;case "aiheading":d=_.template(a("#"+d+"PreviewTemplate").html());
c.html(d({id:f}));g();break;case "activity":d=_.template(a("#activityPreviewTemplate").html());c.html(d({id:f}));break;case "video":O=!0;A(f);break;case "audio":O=!0;A(f);break;case "pdf":d=_.template(a("#pdfPreviewTemplate").html());c.html(d({id:f}));0==c.find("iframe").length?g():X.init(f);break;case "file":aa(f);break;case "code":ba(f);break;case "assignment":d=_.template(a("#assignmentPreviewTemplate").html());c.html(d({id:f}));break;case "livetest":case "assessment":ca=!0;b=_.template(a("#assessmentPreviewTemplate").html());
c.html(b({id:f,type:d}));I&&coursePlayer.hideLoader();break;case "scorm":x(f);break;case "liveclass":O=!0;p(f);break;case "liveclassrecording":O=!0,v(f)}c[0].scrollTo(0,0)}function e(){var b=k.find(".selected").data("type");if(-1<["assessment","livetest"].indexOf(b)||0===z||!C)return!1;b=parseInt(a("#courseTime").data("time"))+z;a("#courseTime").data("time",b).text(formatSeconds(b));b={itemId:k.find(".selected").data("id"),time:z};0<ha&&(b.videoSeekTime=ha,ha=0);postData({url:ctx+"/courses/"+T+"/time/update",
data:b,success:function(b,f){void 0!==b.timeRemaining&&0>=b.timeRemaining&&(J(),a("body").html('<div class="text-center bg-gray centered" style="padding: 50px;border-radius: 10px;margin-top:calc(50vh - 130px);width: 1000px;max-width: 100%;"><h2 class="text-error">Your Course has expired !</h2><h5>You have finished your viewing time.</h5><br><a href="/s/mycourses" class="btn btn-lg btn-success">Go to My Courses</a></div>'))}},{})}function h(b){if(a(b).hasClass("courseSubItem")){var d=a(b).closest(".courseItem");
d.find("input[name=accordion-radio]").is(":checked")||d.find(".accordion-header").trigger("click")}scrollToElement(b)}function ma(b){J();var d=_.template(a("#buyCourseTemplate").html()),f=k.find(".enabled-false, .enabled-true");c.html(d({}));k.find(".selected").removeClass("selected").removeClass("bg-secondary");a(b).addClass("selected").addClass("bg-secondary");f.index(a(b))==f.length-1?r.attr("disabled",!0):r.removeAttr("disabled");0==f.index(a(b))?E.attr("disabled",!0):E.removeAttr("disabled");
c.data("id",a(b).data("id"))}function J(){if(ia){var a=0<c.find("canvas").length?u.video:c.find("video, audio")[0];a.pause();null!=B&&(B.detachMedia(a),B.destroy(),B=null);ia=!1}null!=W&&(window.clearInterval(W),W=null);null!=ra&&(window.clearInterval(ra),ra=null);K=!1}function ja(b){if(0<a(".courseHome").length)return!1;var d=a(b);d.data("id");J();e();z=0;C=!1;var f=a(b).data("liveend"),L=_.template(a("#itemNotLiveTemplate").html()),U=k.find(".enabled-false, .enabled-true");b={startDate:convertDateTime(new Date(a(b).data("live")))};
void 0!==f&&""!==f&&(b.endDate=convertDateTime(new Date(f)));c.html(L({item:b}));g();k.find(".selected").removeClass("selected").removeClass("bg-secondary");d.addClass("selected").addClass("bg-secondary");U.index(d)==U.length-1?r.attr("disabled",!0):r.removeAttr("disabled");0==U.index(d)?E.attr("disabled",!0):E.removeAttr("disabled");r.removeClass("completeItem");c.data("id",d.data("id"))}function ka(b){if(0<a(".courseHome").length)return!1;b=a(b);var d=b.data("id");J();e();z=0;C=!1;for(var f=_.template(a("#itemLockedTemplate").html()),
L=k.find(".enabled-false, .enabled-true"),U="",t=w.indexOf(d)-1;-1<t;t--){var Y=k.find("[data-id="+w[t]+"]");if(Y.hasClass("enabled-true")&&Y.hasClass("completed-false")){U=w[t];break}}c.html(f({id:U})).data("id",d);g();c.find(".gotoItem").on("click",function(b){b=a(this).data("id");b=k.find("[data-id="+b+"]");b.hasClass("courseSubItem")?b.trigger("click"):b.find(".citem").trigger("click");G.makeVisible(b)});k.find(".selected").removeClass("selected").removeClass("bg-secondary");b.addClass("selected").addClass("bg-secondary");
L.index(b)==L.length-1?r.attr("disabled",!0):r.removeAttr("disabled");0==L.index(b)?E.attr("disabled",!0):E.removeAttr("disabled");r.removeClass("completeItem")}function x(b){var d=_.template(a("#scormPreviewTemplate").html());c.html(d({id:b}));if(0==c.find("iframe").length)g();else if(b=c.find("iframe")[0],d=b.document,b.contentDocument?d=b.contentDocument:b.contentWindow&&(d=b.contentWindow.document),/loaded|complete|uninitialized/.test(d.readyState))l();else c.find("iframe").contents().off("load").on("load",
function(){l()})}function Ca(b,d){var f=_.template(a("#"+d+"PreviewTemplate").html());c.html(f({id:b}));X.init(b);"link"===d&&setTimeout(function(){0<c.find("iframe").length&&R(d,b)},3E3)}function v(b){getData({url:M+"/liveclassrecordings/"+b+"/get",data:{},success:function(d,f){d=JSON.parse(parseJData(d.data,!0));f=_.template(a("#liveRecordingPreviewTemplate").html());c.html(f({id:d["spayee:resource"]["spayee:liveclassId"],recordingId:b}));coursePlayer.hideLoader();l()}},{})}function q(a,b){na&&
clearTimeout(na);na=setTimeout(function(){p(a)},b)}function p(b){if(I){var d=d=_.template(a("#liveclassPreviewTemplate").html());c.html(d({}));coursePlayer.hideLoader()}else getData({url:M+"/liveclasses/"+b+"/get",data:{chatToken:!0},success:function(d,e){var f=JSON.parse(parseJData(d.data,!0)),t=null;"youtubelive"===f["spayee:resource"]["spayee:type"]&&0<c.find("iframe").length&&(f["spayee:resource"]["spayee:startTime"]>Date.now()?(f.secondsTillLive=(f["spayee:resource"]["spayee:startTime"]-Date.now())/
1E3,q(b,f["spayee:resource"]["spayee:startTime"]-Date.now())):f["spayee:resource"]["spayee:endTime"]>Date.now()?q(b,f["spayee:resource"]["spayee:endTime"]-Date.now()):f.ended=!0);segmentTrack("Course Item completion",{event:"course_item_completion",properties:{courseId:T,courseName:courseName,itemId:f._id,itemName:f["spayee:resource"]["spayee:title"],contentType:f["spayee:resource"]["spayee:type"]}});segmentTrack("Live Class Attended",{event:"live_class_attended",properties:{courseId:T,courseName:courseName,
liveclassId:f._id,liveclassName:f["spayee:resource"]["spayee:title"]}});t=_.template(a("#bbbliveclassPreviewTemplate").html());d=t({item:f});c.html(d);"graphylive"===f["spayee:resource"]["spayee:type"]&&0<c.find("iframe").length&&(K=!0);"youtubelive"===f["spayee:resource"]["spayee:type"]&&0<c.find("iframe").length&&(a("#discussions-cont").hide(),"plyr"==f["spayee:resource"]["spayee:player"]&&new Plyr("#player"),void 0===f["spayee:resource"]["spayee:chatSupport"]||f["spayee:resource"]["spayee:chatSupport"]||
(a(".chatColumn").find("input, button").attr("disabled",!0),a("#chatsCont").removeClass("loading"),g(),a(".chatColumn").find(".panel").addClass("bg-gray").find(".panel-title").html(_.template(a("#liveRecordingPreviewTemplate").html()))),0!=f.secondsTillLive||f.ended||Da(b,f["spayee:resource"]["spayee:title"],f.chatToken));c.find(".viewRecordingBtn").off("click").on("click",function(d){1===a(this).data("version")?Ea(b,f["spayee:resource"]["spayee:recordingId"]):(t=_.template(a("#liveRecordingPreviewTemplate").html()),
c.html(t({id:b,recordingId:f["spayee:resource"]["spayee:recordingId"]})),l())});oa&&clearInterval(oa);coursePlayer.hideLoader();0==c.find("iframe").length&&0==c.find(".zoomCont").length?0<c.find(".countdown").length?ea.init(function(){p(b)},f):void 0!==f["spayee:resource"]["spayee:streamEnded"]&&f["spayee:resource"]["spayee:streamEnded"]||(W=setInterval(function(){getData({url:M+"/liveclasses/"+b+"/get",data:{},success:function(a,d){void 0!==JSON.parse(parseJData(a.data,!0)).url&&(window.clearInterval(W),
p(b))}},{})},1E4)):"spayeelive"===f["spayee:resource"]["spayee:type"]?(960<=a(window).width()&&a(".off-canvas").hasClass("off-canvas-sidebar-show")&&a(".off-canvas-toggle").trigger("click"),void 0!==f["spayee:resource"]["spayee:isLive"]&&f["spayee:resource"]["spayee:isLive"]&&l()):"youtubelive"===f["spayee:resource"]["spayee:type"]?oa=setInterval(function(){getData({url:M+"/liveclasses/"+b+"/get",data:{},success:function(b,d){b=JSON.parse(parseJData(b.data,!0));void 0===b["spayee:resource"]["spayee:chatSupport"]||
b["spayee:resource"]["spayee:chatSupport"]?(a(".chatColumn").find("input, button").removeAttr("disabled"),a(".chatColumn").find(".panel").removeClass("bg-gray").find(".panel-title").text("Ask your Doubts")):(a(".chatColumn").find("input, button").attr("disabled",!0),a(".chatColumn").find(".panel").addClass("bg-gray").find(".panel-title").html(_.template(a("#liveRecordingPreviewTemplate").html())))}},{})},1E4):void 0!==f["spayee:resource"]["spayee:isLive"]&&f["spayee:resource"]["spayee:isLive"]&&l()}},
{})}function Ea(b,d){getData({url:M+"/liveclasses/"+b+"/videos/"+d+"/get",data:{},success:function(f,e){n=f;f=n["spayee:resource"]["spayee:type"];e="";if(void 0!=n["spayee:resource"]["spayee:underProcess"]&&n["spayee:resource"]["spayee:underProcess"])return e=_.template(a("#courseProcessingTemplate").html()),c.html(e({type:f})),g(),!1;if(null!=n["spayee:resource"]["spayee:completed"]&&!n["spayee:resource"]["spayee:completed"])return e=_.template(a("#courseProcessingFailedTemplate").html()),c.html(e({type:f})),
g(),!1;K=!0;var h=e="";h=_.template(a("#videoPreviewTemplate").html());var t=k.find("[data-id='"+d+"']").data("seekTime"),Y=!1;e=n["spayee:resource"]["spayee:streamUrl"];n.drmPlayerSupport?Y=D():ua()||(B=new Hls({}));K=void 0!==n["spayee:resource"]["spayee:allowWatermark"]?n["spayee:resource"]["spayee:allowWatermark"]:!0;n.drmPlayerSupport&&(K=!1);k.find("[data-id='"+b+"']").hasClass("completed-true")||r.removeAttr("disabled").addClass("completeItem");var F=n["spayee:resource"]["spayee:coverVersion"];
F=F?F:(new Date).getTime();h=h({type:f,url:e,coverVersion:F,id:n._id,autoplay:void 0!==n["spayee:resource"]["spayee:autoplay"]?n["spayee:resource"]["spayee:autoplay"]:!0,description:n["spayee:resource"]["spayee:description"],ctxt:n["spayee:resource"]["spayee:context"],title:n["spayee:resource"]["spayee:title"],isCaption:!!n["spayee:resource"].isCaption,captions:n["spayee:resource"].captions,hparam:void 0!==n["spayee:resource"]["spayee:hparam"]?n["spayee:resource"]["spayee:hparam"]:""});var sa=n["spayee:resource"],
p=n._id;F=n.drmLicenceAvailable;var m=n.drmPlayerSupport;c.html(h);if("upload"===f||"audio"===f)if(0==c.find("video, audio, canvas").length)g();else{g();var n=null;n=null==document.getElementById("vcanvas")?c.find("audio"===f?"audio":"video")[0]:document.createElement("video");if(m)H(n,e,Y,F,sa,p);else{if(!Hls.isSupported()||0<c.find("canvas").length&&Aa)if(iosPlayVideo)n.setAttribute("src",e.replace("/w/","/wi/")),c.find(".video-loader").hide(),c.find(".video-controls").css("opacity",1),l(),bindCustomControls(n,
null,sa,p);else{c.html("<div class='text-center mt-2'>Playback not supported on this device</div>");return}else B.loadSource(e),B.attachMedia(n),B.on(Hls.Events.MANIFEST_PARSED,function(){void 0!==t&&(n.currentTime=t);c.find(".video-loader").hide();c.find(".video-controls").css("opacity",1);l();bindCustomControls(n,B,sa,p)});Ba(n)}n.onwaiting=function(){y=!0;c.find(".video-loader").show()};n.onpause=function(a){y=!0;c.find(".video-loader").hide()};n.onplaying=function(a){c.find(".video-loader").hide()};
n.ontimeupdate=function(a){y=!1;Z(d,parseInt(n.currentTime))};n.onended=function(b){y=!0;0<c.find("video").length&&a(".video-controls").css("opacity","1")};ia=!0}}},{})}function Da(b,d,c){960<=a(window).width()&&a(".off-canvas").hasClass("off-canvas-sidebar-show")&&a(".off-canvas-toggle").trigger("click");var f=!1,e=_.template(a("#chatTemplate").html()),t=a("#chatsCont");var k=ya.collection("chats").doc(b);firebase.auth().signInWithCustomToken(c).then(function(){k.set({name:d,created:firebase.firestore.FieldValue.serverTimestamp(),
expireAt:firebase.firestore.Timestamp.fromDate(new Date(Date.now()+2592E6))},{merge:!0}).then(function(){console.log("Document successfully written!")}).catch(function(a){console.error("Error writing document: ",a)});k.collection("users").doc(SPUSER.id).onSnapshot(function(b){"Server"===(b.metadata.hasPendingWrites?"Local":"Server")&&"Doubt Clearance is not available"!==a(".chatColumn").find(".panel").find(".panel-title").text()&&((f=void 0!==b.data()&&void 0!==b.data().isBlocked&&b.data().isBlocked)?
(a("#chatForm").find(".form-input-hint").text("You are blocked !").show(),a(".chatColumn").find("input, button").attr("disabled",!0)):(a("#chatForm").find(".form-input-hint").text("").hide(),a(".chatColumn").find("input, button").removeAttr("disabled")))});k.collection("messages").orderBy("date").onSnapshot(function(b){b.docChanges().forEach(function(b){"added"===b.type&&(500<t.find("div").length&&t.find("div:lt("+(a("#chatsCont").find("div").length-500)+")").remove(),t.append(e({item:b.doc.data(),
id:b.doc.id})));"removed"===b.type&&t.find("#"+b.doc.id).remove()});t.removeClass("loading");scrollToBottom(t[0])},function(a){})}).catch(function(b){a(".chatColumn").find(".panel-body").removeClass("loading").html("<p class='text-error text-center p-2'>Something went wrong. Please refresh the page.</p>");a(".chatColumn").find("input, button").attr("disabled",!0)});a(".emojiBtns").on("click","button",function(b){b=a("#chatTxt").val();a("#chatTxt").val(b+a(this).text())});var g=0;a("#chatForm").off("submit").on("submit",
function(b){b.preventDefault();b=a.trim(a("#chatTxt").val());var d=a(this).find("button");if(""===b)showAlert("red","Text can't be empty");else if(3E4>(new Date).getTime()-g)showAlert("green","Please wait for "+parseInt(30-((new Date).getTime()-g)/1E3)+" seconds before posting the next message.");else{if(f)return!1;d.addClass("loading").attr("disabled",!0);b={date:firebase.firestore.FieldValue.serverTimestamp(),txt:b,uname:""!==SPUSER.name?SPUSER.name:"Learner",uid:SPUSER.id,expireAt:new Date(Date.now()+
864E5)};k.collection("messages").add(b).then(function(b){console.log("Document written with ID: ",b.id);a("#chatTxt").val("");d.removeClass("loading").removeAttr("disabled");g=(new Date).getTime()}).catch(function(a){showAlert("red","Unable to send chat :: "+a);d.removeClass("loading").removeAttr("disabled")});return!1}});a("#liveChatBtn").off("click").on("click",function(b){a(".chatColumn").is(":visible")?a(".customVidPlayer").removeClass("col-8").addClass("col-12"):(a(".chatColumn").show(),a(".customVidPlayer").addClass("col-8").removeClass("col-12"),
a(".off-canvas").hasClass("off-canvas-sidebar-show")&&a(".off-canvas-toggle").trigger("click"))})}function A(b){getData({url:M+"/videos/"+b+"/get",data:{},success:function(d,f){if(void 0===d["spayee:resource"]["spayee:isAvailable"]||d["spayee:resource"]["spayee:isAvailable"]){m=d;d=m["spayee:resource"]["spayee:type"];if(void 0!=m["spayee:resource"]["spayee:underProcess"]&&m["spayee:resource"]["spayee:underProcess"])return c.html('<h2 class="text-center text-error" style="margin-top: 100px;">'+("audio"===
d?"Audio":"Video")+" is still under processing.<br> Please check back after some time.</h2>"),g(),!1;if(null!=m["spayee:resource"]["spayee:completed"]&&!m["spayee:resource"]["spayee:completed"])return c.html('<h2 class="text-center text-error" style="margin-top: 100px;">'+("audio"===d?"Audio":"Video")+" Processing Failed.<br> Please contact your admin.</h2>"),g(),!1;K=!0;f="";var e=m["spayee:resource"]["spayee:uploadVideoOnlineLink"],h="";h=_.template(a("#videoPreviewTemplate").html());var t=k.find("[data-id='"+
b+"']").data("seekTime"),p=!1;"embedCode"!==d&&("sproutvideo"===d?f=m["spayee:resource"]["spayee:sproutvideoLink"]:"vimeo"===d?f=vimeoVideoId(m["spayee:resource"]["spayee:vimeoLink"]):"youtube"===d?f=youtubeVideoId(m["spayee:resource"]["spayee:youtubeLink"]):void 0!==e&&""!==e?-1<e.indexOf("youtube.com")?(d="youtube",f=youtubeVideoId(e)):-1<e.indexOf("vimeo.com")&&(d="vimeo",f=vimeoVideoId(e)):"link"!==d&&(f=m["spayee:resource"]["spayee:streamUrl"],m.drmPlayerSupport?p=D():ua()||(B=new Hls({}))));
void 0!==m["spayee:resource"]["spayee:allowWatermark"]&&(K=m["spayee:resource"]["spayee:allowWatermark"]);m.drmPlayerSupport&&(K=!1);e=(e=m["spayee:resource"]["spayee:coverVersion"])?e:(new Date).getTime();h=h({type:d,url:f,coverVersion:e,id:m._id,link:void 0!==m["spayee:resource"]["spayee:link"]?m["spayee:resource"]["spayee:link"]:"",autoplay:void 0!==m["spayee:resource"]["spayee:autoplay"]?m["spayee:resource"]["spayee:autoplay"]:!0,ctxt:m["spayee:resource"]["spayee:context"],description:m["spayee:resource"]["spayee:description"],
title:m["spayee:resource"]["spayee:title"],isCaption:!!m["spayee:resource"].isCaption,captions:m["spayee:resource"].captions,hparam:void 0!==m["spayee:resource"]["spayee:hparam"]?m["spayee:resource"]["spayee:hparam"]:""});var F=m["spayee:resource"];e=m.drmLicenceAvailable;var x=m.drmPlayerSupport,v=m._id;c.html(h);MathJax.Hub.Config({menuSettings:["tex2jax.js"],jax:["input/TeX","output/HTML-CSS"],tex2jax:{inlineMath:[["$","$"],["\\(","\\)"]],displayMath:[["$$","$$"],["\\[","\\]"]],processEscapes:!0},
"HTML-CSS":{availableFonts:["TeX"]}});MathJax.Hub.Queue(["Typeset",MathJax.Hub,c.find(".video-description")[0]]);X.init(b);if("upload"===d||"audio"===d||"link"===d){if(g(),0!=c.find("video, audio, canvas").length){var m=null;m=null==document.getElementById("vcanvas")?c.find("audio"===d?"audio":"video")[0]:document.createElement("video");if("link"===d)c.find(".video-loader").hide(),c.find(".video-controls").css("opacity",1),l(),bindCustomControls(m,B);else{if(x)H(m,f,p,e,F,v);else if(!Hls.isSupported()||
0<c.find("canvas").length&&Aa)if(iosPlayVideo)m.setAttribute("src",f.replace("/w/","/wi/")),c.find(".video-loader").hide(),c.find(".video-controls").css("opacity",1),l(),bindCustomControls(m,null,F,v);else{c.html("<div class='text-center mt-2'>Playback not supported on this device</div>");return}else B.loadSource(f),B.attachMedia(m),B.on(Hls.Events.MANIFEST_PARSED,function(){void 0!==t&&(m.currentTime=t);c.find(".video-loader").hide();c.find(".video-controls").css("opacity",1);l();bindCustomControls(m,
B,F,v)});Ba(m)}m.onwaiting=function(){y=!0;c.find(".video-loader").show()};m.onpause=function(a){y=!0;c.find(".video-loader").hide()};m.onplaying=function(a){c.find(".video-loader").hide()};m.ontimeupdate=function(a){y=!1;Z(b,parseInt(m.currentTime))};m.onended=function(b){y=!0;0<c.find("video").length&&a(".video-controls").css("opacity","1")};ia=!0}}else if("vimeo"===d){var n=new Vimeo.Player(a("#text").find("iframe").attr("id"));n.on("loaded",function(a){g();l();n.play();n.setCurrentTime(t)});n.on("timeupdate",
function(a){y=!1;Z(b,parseInt(a.seconds))});n.on("pause",function(a){y=!0});n.on("ended",function(a){y=!0})}else if("youtube"===d)var q=a("#text").find("iframe").attr("id"),J=new YT.Player(q,{events:{onReady:function(d){g();l();d.target.playVideo();d.target.seekTo(t);V=setInterval(function(){0<a("#text").find("#"+q).length?Z(b,parseInt(J.getCurrentTime())):window.clearInterval(V)},1E3)},onStateChange:function(a){switch(a.data){case YT.PlayerState.ENDED:y=!0;break;case YT.PlayerState.PAUSED:y=!0;break;
case YT.PlayerState.PLAYING:y=!1;break;case YT.PlayerState.BUFFERING:y=!0}}}});else if("sproutvideo"===d){var S=new SV.Player({videoId:f.split("?")[0].split("/")[4]}),r=!0;g();S.play();S.bind("play",function(a){l();r&&(r=!1,S.seek(t));y=!1});S.bind("pause",function(a){y=!0});S.bind("completed",function(){y=!0});S.bind("progress",function(a){Z(b,parseInt(a.data.time))})}else"embedCode"===d&&(g(),l())}else Q(d["spayee:resource"]["spayee:startTime"],d["spayee:resource"]["spayee:endTime"])}},{})}function Ba(a){var b=
document.getElementById("vcanvas");if(null!=b){var f=function(){if(u.cheight!=b.parentElement.height||u.cwidth!=b.parentElement.width)b.height=b.parentElement.clientHeight,b.width=b.parentElement.clientWidth,u.cheight=b.height,u.cwidth=b.width,u.scale=Math.min(b.width/u.video.videoWidth,b.height/u.video.videoHeight);e.clearRect(0,0,b.width,b.height);if(void 0!==u&&u.ready){var d=u.scale,c=u.video.videoHeight,k=u.video.videoWidth,g=b.height/2-c/2*d,h=b.width/2-k/2*d;e.drawImage(u.video,h,g,k*d,c*d);
void 0!==u.watermark&&(d=u.watermark.text,c=e,g=u.watermark.top+g,h=u.watermark.left+h,k=d.length,k*=6.2,k>b.width&&(k=b.width),h+15>b.width&&(h=b.width-15),c.fillStyle="RGBA(255, 255, 255, 0.4)",c.fillRect(g-k/2,h-7.5,k,15),c.font=(10).toString()+"px monospace",c.fillStyle="black",c.textBaseline="middle",c.textAlign="center",c.fillText(d,g,h))}a.requestVideoFrameCallback(f)},c=function(d){u.scale=Math.min(b.width/this.videoWidth,b.height/this.videoHeight);u.ready=!0;a.requestVideoFrameCallback(f);
a.play()};u={video:a,isReady:!1};var e=b.getContext("2d",{alpha:!1});b.height=b.parentElement.clientHeight;b.width=b.parentElement.clientWidth;a.oncanplay=c;a.oncanplaythrough=c;u.cheight=b.height;u.cwidth=b.width}}function D(){a(".customVidPlayer > .error-msg").hide();var b=navigator.userAgentData;shaka.polyfill.installAll();var d;if(d=shaka.Player.isBrowserSupported())a:{if(void 0!==b){d=$jscomp.makeIterator(b.brands);for(var c=d.next();!c.done;c=d.next())if("Chromium"==c.value.brand){d=!0;break a}}d=
!1}return d&&-1<b.platform.toLowerCase().indexOf("win")?!0:!1}function H(b,d,c,e,k,t){function f(b){a(".customVidPlayer .video-loader").hide();a(".customVidPlayer > .error-msg").text(b).show()}if(e&&d&&d.endsWith("playlist.mpd"))if(c){var h=function(a){f("Playback not supported, please contact admin.");console.error("Error code",a.code,"object",a)},g=new shaka.Player(b);g.configure({drm:{servers:{"com.widevine.alpha":"https://widevine-dash.ezdrm.com/widevine-php/widevine-foreignkey.php?pX=6370EB&CustomData="+
btoa(d)}}});g.addEventListener("error",function(a){h(a.detail)});g.load(d).then(function(){console.log("The video has now been loaded!");bindCustomControls(b,null,k,t,g)}).catch(h)}else f("This browser is not supported. Please use Google Chrome on Windows operating system.");else f("Playback not supported, please contact admin.")}function Z(a,b){15<Math.abs(k.find("[data-id='"+a+"']").data("seekTime")-b)&&(k.find("[data-id='"+a+"']").data("seekTime",b),I||(ha=b))}function N(a){var b=a.height();var e=
a.width();var f=(Math.random()+1).toString(36).substring(7);(Math.random()+1).toString(36).substring(7);b=Math.floor(Math.random()*(b-70+1));0<a.find("canvas").length?(e=Math.floor(Math.random()*e),console.log("showwatermark - top: "+b+" ,left: "+e),u.watermark={text:location.host+" | "+pa+" | "+qa,top:b,left:e},setTimeout(function(){console.log("deletewatermark;");delete u.watermark},1E3*fa)):(e=Math.floor(Math.random()*(e-100+1)),e="<div class='"+f+"' style='border-radius: 5px;padding: 2px;opacity:0.7;font-size:10px;background:white;z-index:5;position:absolute;top:"+
b+"px;left:"+e+"px;text-align:center;'>"+location.host+"<br>"+pa+"<br>"+qa+"</div>",0==b%2?a.after(e):a.before(e),setTimeout(function(){c.find("div."+f).remove()},1E3*fa))}function aa(b){var d=_.template(a("#filePreviewTemplate").html());c.html(d({id:b}));if(0==c.find("iframe").length)g();else{d=c.find("iframe")[0];var e=d.document;d.contentDocument?e=d.contentDocument:d.contentWindow&&(e=d.contentWindow.document);coursePlayer.hideLoader();if(/loaded|complete|uninitialized/.test(e.readyState))l();
else c.find("iframe").contents().off("load").on("load",function(){l()});X.init(b)}}function ba(b){var d=_.template(a("#codePreviewTemplate").html());c.html(d({id:b}));if(0==c.find("iframe").length)g();else{d=c.find("iframe")[0];var e=d.document;d.contentDocument?e=d.contentDocument:d.contentWindow&&(e=d.contentWindow.document);coursePlayer.hideLoader();if(/loaded|complete|uninitialized/.test(e.readyState))l();else c.find("iframe").contents().off("load").on("load",function(){l()});X.init(b)}}var V=
null,ia=!1,B=null,T,I,ea=function(){function b(a){var b=parseInt(a/86400%365*100)/100,c=parseInt(a/3600%24*100)/100,e=parseInt(a/60%60*100)/100;a=parseInt(a%60);var d="";1<=b&&(d=d+(10>b?"0":"")+parseInt(b)+"d ");0<=c&&(d=d+(10>c?"0":"")+parseInt(c)+"h ");0<=e&&(d=d+(10>e?"0":"")+parseInt(e)+"m ");0<=a&&(d=d+(10>a?"0":"")+a+"s");return""!==d?d:0}return{init:function(d,c){var e=a(".countdown"),f=e.data("secs"),t;86400<f?e.html(convertDateTime(new Date(c["spayee:resource"]["spayee:startTime"]))):t=
setInterval(function(){e.html(b(f));if(0>=f||"graphylive"===c["spayee:resource"]["spayee:type"]&&600>f)clearInterval(t),d();f--},1E3)}}}(),X=function(){return{init:function(b){try{if(0!=a("#discussions-template").length){var d=_.template(a("#discussions-template").html());a(".itemDiscussions").text(0);a(".totalDiscussions").text(0);xa.show();c.append(d({isSample:I}));discussions.initCItemMode(T,b)}}catch(F){console.log(F)}}}}();return{init:function(f,d,g){T=f;I=d;if(!I){var p=setInterval(function(){C&&
(e(),z=0)},6E4);ifvisible.on("idle",function(){console.log("idleeee"+new Date);O||ca||(console.log("timer stopped"),window.clearInterval(p),p=null)});ifvisible.on("wakeup",function(){console.log("wakeupeee"+new Date);O||ca||(z=0);null===p&&(console.log("timer started"),p=setInterval(function(){C&&(e(),z=0)},6E4))})}setInterval(function(){K&&(0<c.find("video").length?N(c.find("video")):0<c.find("canvas").length?N(c):0<c.find("iframe").length&&N(a(c.find("iframe")[0])))},1E3*(za+fa));if(0<k.find(".chip.upcoming").length)var l=
setInterval(function(){var b=k.find(".chip.upcoming");0<b.length?b.each(function(){var b=a(this).data("started");void 0!==b&&P>b&&a(this).removeClass("upcoming").addClass("live").text("live")}):clearInterval(l)},1E3);a(".courseItem .citem").off("click").on("click",function(d){d=a(this).closest(".courseItem");d.find("input[name=accordion-radio]").is(":checked")||d.find(".accordion-header").trigger("click");if("label"===d.data("type"))return!1;if(void 0!==d.data("live")&&""!==d.data("live")){var c=
d.data("liveend"),e=d.data("live");if(void 0===c||""===c)c=(new Date).getTime()+36E5;P>e&&c>P?d.addClass("enabled-true").removeClass("enabled-false"):d.addClass("enabled-false").removeClass("enabled-true")}c=w.indexOf(d.data("id"));e=!1;for(var f=c-1;-1<f;f--){var g=k.find("[data-id="+w[f]+"]");if(g.hasClass("prereqItem")){e=!0;break}}var h=!1;if("true"===sequentialAccess||e){var t=!1;for(f=c-1;-1<f;f--)if(g=k.find("[data-id="+w[f]+"]"),"true"===sequentialAccess){if(g.hasClass("enabled-true")&&g.hasClass("completed-false")){t=
!0;break}}else if(e&&g.hasClass("prereqItem")&&g.hasClass("enabled-true")&&g.hasClass("completed-false")){t=!0;break}t&&d.hasClass("enabled-true")&&(d.addClass("enabled-false").removeClass("enabled-true"),h=!0)}d.hasClass("enabled-true")?b(d[0]):I?ma(d[0]):void 0===d.data("live")||""===d.data("live")||h?ka(d[0]):ja(d[0])});a(".courseSubItem").off("click").on("click",function(d){d.stopPropagation();d=a(this);var c=d.closest(".courseItem");c.find("input[name=accordion-radio]").is(":checked")||c.find(".accordion-header").trigger("click");
if("label"===d.data("type"))return!1;if(void 0!==d.data("live")&&""!==d.data("live")){c=d.data("liveend");var e=d.data("live");if(void 0===c||""===c)c=(new Date).getTime()+36E5;P>e&&c>P?d.addClass("enabled-true").removeClass("enabled-false"):d.addClass("enabled-false").removeClass("enabled-true")}c=w.indexOf(d.data("id"));e=!1;for(var f=c-1;-1<f;f--){var g=k.find("[data-id="+w[f]+"]");if(g.hasClass("prereqItem")){e=!0;break}}var h=!1;if("true"===sequentialAccess||e){var p=!1;for(f=c-1;-1<f;f--)if(g=
k.find("[data-id="+w[f]+"]"),"true"===sequentialAccess){if(g.hasClass("enabled-false")||g.hasClass("enabled-true")&&g.hasClass("completed-false")){p=!0;break}}else if(e&&(g.hasClass("enabled-false")||g.hasClass("prereqItem")&&g.hasClass("enabled-true")&&g.hasClass("completed-false"))){p=!0;break}p&&d.hasClass("enabled-true")&&(d.addClass("enabled-false").removeClass("enabled-true"),h=!0)}d.hasClass("enabled-true")?b(this):I?ma(this):void 0===d.data("live")||""===d.data("live")||h?ka(this):ja(this)});
r.off("click").on("click",function(a){r.hasClass("completeItem")?(a=w.indexOf(c.data("id")),a=k.find("[data-id="+w[a]+"]"),va(c.data("id")),segmentTrack("Course Item completion",{event:"course_item_completion",properties:{courseId:T,courseName:wa,itemId:c.data("id"),itemName:a.data("title"),contentType:a.data("type")}})):ta()});E.off("click").on("click",function(a){a=w.indexOf(c.data("id"))-1;a=k.find("[data-id="+w[a]+"]");a.hasClass("courseSubItem")?a.trigger("click"):a.find(".citem").trigger("click");
h(a)});a(document).keydown(function(b){if(!a(document.activeElement).is("input")&&!a(document.activeElement).is("textarea")){switch(b.which){case 37:0<a(".customVidPlayer").length?a("#replay-10").trigger("click"):E.trigger("click");break;case 39:0<a(".customVidPlayer").length?a("#forward-10").trigger("click"):r.trigger("click");break;case 32:if(0<a(".customVidPlayer").length){var d=a(".customVidPlayer").find("video")[0];d.paused?d.play():d.pause()}break;default:return}b.preventDefault()}})},makeVisible:h,
updateTimeSpent:e,showBuyCourse:ma}}();return{init:function(c,l,r,u,J,ja,ka,x,A,v){segmentTrack("Course Page Visit",{event:"course_page_visit",properties:{courseId:c,courseName:v}});""!==a("#wduration").val()&&(v=parseInt(a("#wduration").val()),0<v&&(fa=v));""!==a("#winterval").val()&&(v=parseInt(a("#winterval").val()),0<v&&(za=v));P=ka;D=c;N=u;ea=J;pa=l;qa=r;V=ja;H=A;aa();ifvisible.setIdleDuration(300);a(window).resize(function(){aa()});G.init(D,N,ea);k.find(".courseItem").each(function(){"label"!==
a(this).data("type")&&(ba.push({id:a(this).data("id"),type:a(this).data("type")}),w.push(a(this).data("id")));0<a(this).find(".courseSubItem").length&&a(this).find(".courseSubItem").each(function(){"label"!==a(this).data("type")&&(ba.push({id:a(this).data("id"),type:a(this).data("type")}),w.push(a(this).data("id")))})});a(".certificateItem").on("click",function(b){h();var c=a(".certificate"),e=_.template(a("#certificate-template").html());0<c.length&&c.remove();getData({url:ctx+"/courses/"+D+"/certificate/details",
data:{},success:function(b,h){g();a("body").append(e({data:b}));c=a(".certificate");0<c.find("#share").length&&a("#share").jsSocials({url:location.protocol+"//"+location.host+"/share-certificate?serialno="+b.serialno,text:"I earned a certificate",showCount:!0,showLabel:!1,shares:"email twitter facebook linkedin telegram whatsapp".split(" ")})}},{})});a("#courseDiscussionsBtn").on("click",function(b){""===a("#discussions-cont").find("iframe").attr("src")&&a("#discussions-cont").find("iframe").attr("src",
"/s/courses/"+D+"/discussions");a(".mainCont").hide();a("#discussions-cont").show();da=!0;a(this).addClass("bg-primary");a("#courseTocBtn").removeClass("bg-primary")});a("#courseTocBtn").on("click",function(b){a("#discussions-cont").hide();a(".mainCont").show();da=!1;a(this).addClass("bg-primary");a("#courseDiscussionsBtn").removeClass("bg-primary");0==k.find(".selected").length&&(b=0<k.find(".enabled-true.completed-false").length?k.find(".enabled-true.completed-false:first"):k.find(".enabled-true:last"),
b.hasClass("courseSubItem")?b.trigger("click"):b.find(".citem").trigger("click"))});if(N)M=ctx+"/preview/courses/"+D,a(".courseHome").removeClass("courseHome"),c=location.hash.split("#")[1],q=void 0!==c&&""!==c&&0<k.find("[data-id="+c+"]").length?k.find("[data-id="+c+"]"):k.find(".completed-false.enabled-true:first"),q.hasClass("courseSubItem")?q.trigger("click"):q.find(".citem").trigger("click"),G.makeVisible(q);else{a("#courseProgressCont").find("progress").attr("value",H);a("#courseProgress").text(H+
"%");a("#courseTime").text(formatSeconds(parseInt(a("#courseTime").data("time"))));M=ctx+"/courses/"+D;c=location.hash.split("#")[1];var q=null;if(void 0!==c&&""!==c)if(-1<c.indexOf("discussions"))x="/s/courses/"+D+"/discussions",-1<location.hash.indexOf("discussions-")&&/^[a-f\d]{24}$/i.test(location.hash.split("#")[1].split("discussions-")[1])&&(x=x+"#"+location.hash.split("#")[1].split("discussions-")[1]),a("#discussions-cont").find("iframe").attr("src",x),a("#courseDiscussionsBtn").trigger("click"),
a(".courseHome").removeClass("courseHome");else if(-1<c.indexOf("high=")){x=c.split("high=")[1].split(",");for(c=0;c<x.length;c++)k.find(".isNewItem.id-"+x[c]).show();0<x.length?(a(".courseHome").removeClass("courseHome"),x=k.find(".isNewItem:visible:eq(0)"),0<x.closest(".courseSubItem").length?x.closest(".courseSubItem").trigger("click"):x.closest(".courseItem").find(".citem").trigger("click"),G.makeVisible(x)):e()}else 0<c.length?(x=c.split("&")[0],0<k.find("[data-id="+x+"]").length?(a(".courseHome").removeClass("courseHome"),
q=k.find("[data-id="+x+"]"),q.hasClass("courseSubItem")?q.trigger("click"):q.find(".citem").trigger("click"),G.makeVisible(q)):e()):e();else""!==x&&k.find("[data-id="+x+"]").hasClass("enabled-true")?(a(".courseHome").removeClass("courseHome"),q=k.find("[data-id="+x+"]"),q.hasClass("courseSubItem")?q.trigger("click"):q.find(".citem").trigger("click"),G.makeVisible(q)):e();setInterval(function(){y||da||z++;P+=1E3},1E3)}a(window).resize(function(){b()});b();a(document).on("contextmenu",function(a){return!1});
"undefined"!==typeof firebase&&(firebase.initializeApp(firebaseConfig),ya=firebase.firestore());window.addEventListener("hashchange",function(a){a=location.hash.split("#")[1];0<a.length&&(a=a.split("&")[0],0<k.find("[data-id="+a+"]").length&&(q=k.find("[data-id="+a+"]"),q.hasClass("courseSubItem")?q.trigger("click"):q.find(".citem").trigger("click"),G.makeVisible(q)))})},assessmentReports:function(){function b(b,g){g=b.userAssessmentLevelReport[0];var k=b.userQuestionLevelReport[0],l=[],v=null,q=
null,p=null;p=null;if("preCourse"===h["spayee:courseStage"])p=_.template(a("#preCourseTestTemplate").html()),a("#reports").html(p({}));else if(q=void 0===h["spayee:passingPercentage"]?0:h["spayee:passingPercentage"],p=100*g.marksObtained/g.assessmentTotalMarks,"gamified"!==V||p>=q){p=_.template(a("#passReportTemplate").html());sortArray(h["spayee:questions"].question);c(h);a.each(h["spayee:answers"].answer,function(a,b){e[b.questionId]=b});h["spayee:answers"].answer=e;1==b.userAssessmentLevelReport.length?
l=b.userGoalLevelReport:a.each(b.userGoalLevelReport,function(a,b){void 0!==b.questionLevelId&&b.questionLevelId==k._id&&l.push(b)});if(a.isArray(k.userSelectedOptions)){var r={};a.each(k.userSelectedOptions,function(b,c){a.each(c,function(a,b){r[a]=b})});k.userSelectedOptions=r}a("#reports").html(p({item:b,assessment:h,answers:e,assessmentReport:g,questionReport:k,goalReport:l}));MathJax.Hub.Config({menuSettings:["tex2jax.js"],jax:["input/TeX","output/HTML-CSS"],tex2jax:{inlineMath:[["$","$"],["\\(",
"\\)"]],displayMath:[["$$","$$"],["\\[","\\]"]],processEscapes:!0},"HTML-CSS":{availableFonts:["TeX"]}});MathJax.Hub.Queue(["Typeset",MathJax.Hub,document.getElementById("assessment")]);v=new google.visualization.arrayToDataTable([["","Number of Questions",{role:"style"}],["Total",parseInt(g.correctQuestions)+parseInt(g.incorrectQuestions)+parseInt(g.skippedQuestions),"#3366cc"],["Correct",parseInt(g.correctQuestions),"#4CAF79"],["Incorrect",parseInt(g.incorrectQuestions),"#EB5054"],["Skipped",parseInt(g.skippedQuestions),
"#ccc"]]);q={chart:{title:""},legend:{position:"none"},theme:"material"};p=new google.visualization.BarChart(document.getElementById("questionBarChart"));p.draw(v,q);if(1<l.length){v=new google.visualization.DataTable;v.addColumn("string","");v.addColumn("number","Total Questions");v.addColumn("number","Correct Questions");v.addColumn("number","Incorrect Questions");v.addColumn("number","Skipped Questions");var u="";a.each(l,function(a,b){u=void 0!==b.goalName?b.goalName:"";25<u.length&&(u=u.replace(/ /g,
"\n"));v.addRow([u,b.totalQuestions,b.correctQuestions,b.incorrectQuestions,b.skipped])});q={title:"",legend:{position:"top"},colors:["#3366cc","#4CAF79","#EB5054","#ccc"],theme:"material"};p=new google.visualization.ColumnChart(document.getElementById("goalQuestionsBarChart"));p.draw(v,q)}1<b.userAssessmentLevelReport.length&&(v=new google.visualization.DataTable,v.addColumn("string",""),v.addColumn("number","My Marks"),a.each(b.userAssessmentLevelReport.reverse(),function(a,b){v.addRow([convertDateTime(new Date(b.createdDate.time)).replace(" ",
"\n"),b.marksObtained])}),q={title:"",legend:{position:"right"},theme:"material"},p=new google.visualization.ColumnChart(document.getElementById("marksAssessmentChart")),p.draw(v,q))}else p=_.template(a("#notPassReportTemplate").html()),a("#reports").html(p({item:b,assessment:h,assessmentReport:g,passingPercentage:q}));iframeLoaded()}function c(b){var c=_.template(a("#fontTemplate").html()),e=[];a.each(b["spayee:questions"].question,function(b,c){void 0!==c.questiongroup&&c.questiongroup&&"false"!=
c.questiongroup?a.each(c.question,function(b,c){void 0!==c.defEncoding&&"unicode"!=c.defEncoding&&0>e.indexOf(c.defEncoding)&&e.push(c.defEncoding);void 0!==c.lang&&a.each(c.lang,function(a,b){void 0!==b.encoding&&0>e.indexOf(b.encoding)&&"unicode"!=b.encoding&&e.push(b.encoding)})}):(void 0!==c.defEncoding&&"unicode"!=c.defEncoding&&0>e.indexOf(c.defEncoding)&&e.push(c.defEncoding),void 0!==c.lang&&a.each(c.lang,function(a,b){void 0!==b.encoding&&0>e.indexOf(b.encoding)&&"unicode"!=b.encoding&&e.push(b.encoding)}))});
a("head").append(c({item:e}))}var e={},g=null,h=null;return{init:function(c,e){var k=location.href.split("#")[0]+"/get";-1<location.href.indexOf("/take")&&(k=ctx+"/courses/"+c+"/assessment/"+e+"/reports/get");getData({url:k,data:{},success:function(c,e){g=JSON.parse(parseJData(c.data,!0));h=g.assessment["spayee:resource"];b(g.practiceReport,!1);void 0!==window.parent.coursePlayer?window.parent.coursePlayer.hideLoader():a(window.parent.document).find("#colorbox").find("iframe").removeClass("loading");
-1<location.href.indexOf("/take")&&window.parent.coursePlayer.restartTimer();a.each(h["spayee:questions"].question,function(b,c){c.questiongroup&&"false"!=c.questiongroup&&a.each(c.question,function(a,b){})})}},{})}}}(),enableNextCourseItem:A,saveActivityInputs:function(a,b){k.find("[data-id='"+a+"']").data("activityData",b)},restoreActivityInputs:function(b){var e=k.find("[data-id='"+b+"']");b={};var g=c.find("iframe").contents();void 0!==e.data("activityData")&&(b=e.data("activityData"),a.each(b,
function(b,c){b=g.find("[name='"+b+"']");var h=b.prop("tagName").toLowerCase(),k=b.eq(0).attr("type");if("input"===h)switch(k){case "checkbox":b.each(function(){"boolean"===typeof c&&c||"boolean"!==typeof c&&-1<c.indexOf(this.value)?a(this).prop("checked",!0):a(this).prop("checked",!1)});break;case "radio":b.filter(function(){return c===a(this).val()}).prop("checked",!0);break;case "file":c&&b.parent().append("<a data-value='"+JSON.stringify(c)+"' href='"+c.path+"'>"+c.name+" ("+formatBytes(c.size)+
")</a>");break;default:b.val(c)}else"textarea"!==h&&"select"!==h||b.val(c);e.hasClass("completed-true")&&b.attr("disabled",!0)}),e.hasClass("completed-true")&&c.find("iframe").contents().find("#submitBtn").remove())},hideLoader:g,showLoader:h,restartTimer:l,showNotAvailableContent:Q,showAvailableContent:R,liveclassEnded:function(b,e,g,h,k){-1<b.indexOf("meetingEnded")&&(c.html(a("#liveclassEndedTemplate").html()),G.updateTimeSpent(),C=!1,z=0,va(c.data("id")),segmentTrack("Live Class Attended",{event:"live_class_attended",
properties:{courseId:h,courseName:k,liveclassId:e,liveclassName:g}}))},courseItemPreview:G,testSubmitted:function(){G.updateTimeSpent();C=!1;z=0}}}(jQuery);
if("WakeLock"in window&&"request"in window.WakeLock){var wakeLock=null,requestWakeLock=function(){var a=new AbortController;window.WakeLock.request("screen",{signal:a.signal}).catch(function(a){"AbortError"===a.name?console.log("Wake Lock was aborted"):console.error(a.name+", "+a.message)});console.log("Wake Lock is active");return a};requestWakeLock();var handleVisibilityChange=function(){null!==wakeLock&&"visible"===document.visibilityState&&(wakeLock=requestWakeLock())};document.addEventListener("visibilitychange",
handleVisibilityChange)}else if("wakeLock"in navigator&&"request"in navigator.wakeLock){var wakeLock$1=null,requestWakeLock$2=function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return b.setCatchFinallyBlocks(2),b.yield(navigator.wakeLock.request("screen"),4);if(2!=b.nextAddress)return wakeLock$1=b.yieldResult,wakeLock$1.addEventListener("release",function(a){console.log(a);console.log("Wake Lock was released")}),console.log("Wake Lock is active"),b.leaveTryBlock(0);
a=b.enterCatchBlock();console.error(a.name+", "+a.message);b.jumpToEnd()})};requestWakeLock$2();var handleVisibilityChange$3=function(){null!==wakeLock$1&&"visible"===document.visibilityState&&requestWakeLock$2()};document.addEventListener("visibilitychange",handleVisibilityChange$3)}else console.error("Wake Lock API not supported.");
